[tools]
go = "1.26.5"
golangci-lint = "2.12.2"
goreleaser = "2.17.1"
"go:go.uber.org/nilaway/cmd/nilaway" = "0.0.0-20251208195206-89df5f7e6199"

[tasks.test]
run = "go test ./... -v -race -cover"

[tasks.lint]
run = "golangci-lint run"

[tasks.build]
run = "go build -o bin/lkm cmd/lkm/main.go"

[tasks.run]
run = "go run cmd/lkm/main.go"

[tasks.install]
run = "go install ./cmd/lkm"

[tasks.nilaway]
run = "nilaway ./..."
