coverage:
  status:
    project:
      default:
        target: 20%
        threshold: 1%
    patch:
      default:
        target: 20%
        threshold: 1%

ignore:
  - "cmd/lkm/main.go"
  - "internal/tui/*.go"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
